apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: yrkesskade
  labels:
    team: yrkesskade
spec:
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "nav:yrkesskade:skademelding.write"
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{this.name}}
       value: "{{this.value}}"
  {{/each}}